name: Linter CI
run-name: ${{github.ref_name}} is linting by @${{ github.actor }} ğŸš€
on: [push, pull_request]

jobs:
  Linters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Setup Ruby"
      - uses: ruby/setup-ruby@v1
      - run: echo "Install gems ğŸ’"
      - run: bundle install
      - run: echo "Run rubocop ğŸ‘®"
      - run: rubocop
      - run: echo "ğŸ This job's status is ${{ job.status }}."
