name: Aeksion linter CI
run-name: ${{ github.actor }} ğŸš€
on: [push, pull_request]

jobs:
  Linters:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install gems ğŸ’
        run: bundle install
      - name: run linters ğŸ‘®
        run: rubocop
      - run: echo "ğŸ This job's status is ${{ job.status }}."
